options:
    servername: <##008080>&lQ<##0E888B>&lu<##1B9095>&la<##2997A0>&ln<##369FAB>&lt<##44A7B6>&lu<##51AFC0>&lm<##5FB7CB>&lG<##6CBED6>&le<##7AC6E0>&ln<##87CEEB>&lz &8»
    discount: 15

on load:
    set {discount} to (100 - {@discount})/100

command /goldtest [<text>]:
    permission: op
    trigger:
        if arg-1 is "save":
            delete file "plugins/Test/gold.txt"
            create file "plugins/Test/gold.txt"
            loop {gold::*}:

                write "%loop-value% | %{goldamount::%loop-value%}%" at line ((line count of file "plugins/Test/gold.txt")+1) to file "plugins/Test/gold.txt"
        else if arg-1 is "import":
            set {_lineamount} to line count of file "plugins/Test/gold.txt"
            loop {_lineamount} times:
                set {_line} to line loop-value in file "plugins/Test/gold.txt"
                #send {_line}
                set {_line::*} to split {_line} at " | "
                set {_name} to ({_line::1} parsed as player)
                set {_amount} to ({_line::2} parsed as number)
                set {goldamount::%{_line::1}%} to ({_line::2} parsed as number)
                send "%{_name}% %{_amount}%"


command /setgold [<offlineplayer>] [<number>]:
    trigger:
        set {gold::%arg-1's uuid%} to arg-1's uuid
        set {goldamount::%arg-1's uuid%} to arg-2

command /resetgold:
    trigger:
        delete {goldamount::*}
        delete {gold::*}

function buyitemGold(input: number, player: player) :: boolean:
	if {goldamount::%{_player}'s uuid%} is less than ({_input}*{discount}):
		send "&7[&c&lError&7] &cInsufficient Funds." to {_player}
		play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
		return false
	else:
		remove ({_input}*{discount}) from {goldamount::%{_player}'s uuid%}
		play sound "block_note_block_pling" with volume 10 and pitch 10 to {_player}
		return true

#100 gems = 1$

#<------------------------------------------------------------------------------------------------------
command /buystore:
    trigger:
        create a gui with virtual chest with 5 rows named "&8&l&nStore&3&l 💎%{goldamount::%player's uuid%}% Gems":
            make gui slot (integers from 0 to 44) with gray stained glass pane named " "
            make gui slot (0, 1, 9, 8, 7, 17, 27, 35, 36, 37, 35, 43, 44) with black stained glass pane named " "
#<--------------------------------------------------------------------------------------------------------------------------------------------------->
            # The mediocre
            make gui slot 10 with glowing map named "&f&lRank Shop" with lore "&7" and "&7click to open":
                rankPage(player)
            make gui slot 11 with blaze rod named "&f&lSellwand Shop" with lore "&7" and "&7click to open":
                sellwandPage(player)
            make gui slot 40 with beacon named "&f&lGem Shop" with lore "&f" and "&7click to open store":
                Send "<##008080>&m===================================" to player
                Send "&b" to player
                Send "<##008080>&lShop >> <link:https://quantumgenz.craftingstore.net/>&f&lClick me to open the shop!<reset>" to player
                Send "&b" to player
                Send "<##008080>&m===================================" to player



        open last gui to player


function rankPage(player: player):
    create a gui with virtual chest with 5 rows named "&8&l&nRanks&3&l 💎%{goldamount::%{_player}'s uuid%}% Gems":
        make gui slot (integers from 0 to 44) with gray stained glass pane named " "
        make gui slot (0, 1, 9, 8, 7, 17, 27, 35, 36, 37, 35, 43, 44) with black stained glass pane named " "
        set {_itemcost} to 700
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 10 with glowing map named "<##008080>&lAstro Rank" with lore "&f" and "&8&l﹁&f Astro prefix" and "&8&l﹁&f 2 plots" and "&8&l﹁&f +10 gen slots" and "&8&l﹁&f 1.2x multi" and "&8&l﹁&f /afk" and "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} doesn't have permission "group.astro":
                if buyitemGold({_itemcost}, {_player}):
                    execute console command "/lp user %{_player}% parent add astro"
                    rankPage({_player})
            else:
                send "{@servername} &cYou already own this rank!"
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}


        set {_itemcost} to 1100
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 11 with glowing map named "<##87CEEB>&lL<##9DDAF0>&lu<##B4E7F5>&ln<##CAF3FA>&la<##E0FFFF>&lr Rank" with lore "&f" and "&8&l﹁&f Lunar prefix" and "&8&l﹁&f 3 plots" and "&8&l﹁&f +20 gen slots" and "&8&l﹁&f 1.5x multi" and "&8&l﹁&f /afk" and "&8&l﹁&f /pickupgens" and "&8&l﹁&f /fly" and "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} doesn't have permission "group.lunar":
                if buyitemGold({_itemcost}, {_player}):
                    execute console command "/lp user %{_player}% parent add lunar"
                    rankPage({_player})
            else:
                send "{@servername} &cYou already own this rank!"
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}

        set {_itemcost} to 1500
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 12 with glowing map named "<##FFD700>&lS<##FFDC23>&lo<##FFE246>&ll<##FFE768>&la<##FFEC8B>&lr Rank" with lore "&f" and "&8&l﹁&f Solar prefix" and "&8&l﹁&f 4 plots" and "&8&l﹁&f +30 gen slots" and "&8&l﹁&f 1.75x multi" and "&8&l﹁&f /afk" and "&8&l﹁&f /pickupgens" and "&8&l﹁&f /fly" and "&8&l﹁&f /upgradegens" and "&8&l﹁&f /nick" and "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} doesn't have permission "group.solar":
                if buyitemGold({_itemcost}, {_player}):
                    execute console command "/lp user %{_player}% parent add solar"
                    rankPage({_player})
            else:
                send "{@servername} &cYou already own this rank!"
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}

        set {_itemcost} to 1800
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 13 with glowing map named "<##D8BFD8>&lC<##DAC4DC>&le<##DCC9E1>&ll<##DDCEE5>&le<##DFD3E9>&ls<##E1D7ED>&lt<##E3DCF2>&li<##E4E1F6>&la<##E6E6FA>&ll Rank" with lore "&f" and "&8&l﹁&f Celestial prefix" and "&8&l﹁&f 7 plots" and "&8&l﹁&f +40 gen slots" and "&8&l﹁&f 2.0x multi" and "&8&l﹁&f /afk" and "&8&l﹁&f /pickupgens" and "&8&l﹁&f /fly" and "&8&l﹁&f /upgradegens" and "&8&l﹁&f /nick" and "&8&l﹁&f /hat" and "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} doesn't have permission "group.celestial":
                if buyitemGold({_itemcost}, {_player}):
                    execute console command "/lp user %{_player}% parent add celestial"
                    rankPage({_player})
            else:
                send "{@servername} &cYou already own this rank!"
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}

        set {_itemcost} to 2300
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 14 with glowing map named "<##5907E0>&lG<##630EE0>&la<##6E16E0>&ll<##781DE0>&la<##8224E1>&lc<##8C2BE1>&lt<##9733E1>&li<##A13AE1>&lc<##AB41E1>&la Rank" with lore "&f" and "&8&l﹁&f Galactica prefix" and "&8&l﹁&f 10 plots" and "&8&l﹁&f +50 gen slots" and "&8&l﹁&f 2.5x multi" and "&8&l﹁&f /afk" and "&8&l﹁&f /pickupgens" and "&8&l﹁&f /fly" and "&8&l﹁&f /upgradegens" and "&8&l﹁&f /nick" and "&8&l﹁&f /hat" and "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} doesn't have permission "group.galactica":
                if buyitemGold({_itemcost}, {_player}):
                    execute console command "/lp user %{_player}% parent add galactica"
                    rankPage({_player})
            else:
                send "{@servername} &cYou already own this rank!"
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}




        set {_itemcost} to 4000
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 15 with glowing map named "<##FFD700>&lQ<##D8DB28>&lu<##B1DF50>&la<##8AE378>&ln<##63E79F>&lt<##3CEBC7>&lu<##15EFEF>&lm Rank" with lore "&f" and "&8&l﹁&f Quantum prefix" and "&8&l﹁&f 12 plots" and "&8&l﹁&f +100 gen slots" and "&8&l﹁&f 3.0x multi" and "&8&l﹁&f /afk" and "&8&l﹁&f /pickupgens" and "&8&l﹁&f /fly" and "&8&l﹁&f /upgradegens" and "&8&l﹁&f /nick" and "&8&l﹁&f /hat" and "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} doesn't have permission "group.quantum":
                if buyitemGold({_itemcost}, {_player}):
                    execute console command "/lp user %{_player}% parent add quantum"
                    rankPage({_player})
            else:
                send "{@servername} &cYou already own this rank!"
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}




        set {_itemcost} to 10000
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 16 with glowing map named rainbow("&lCustom Rank") with lore "&f" and "&8&l﹁&f custom prefix (create discord ticket)" and "&8&l﹁&f 20 plots" and "&8&l﹁&f +100 gen slots" and "&8&l﹁&f +200 hopper slots" and "&8&l﹁&f +5 silo slots" and "&8&l﹁&f 3.5x multi" and "&8&l﹁&f /afk" and "&8&l﹁&f /pickupgens" and "&8&l﹁&f /fly" and "&8&l﹁&f /upgradegens" and "&8&l﹁&f /nick" and "&8&l﹁&f /hat" and "&8&l﹁&f /customchatcolor" and "&8&l﹁&f all /cc colors" and "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} doesn't have permission "group.customrank":
                if buyitemGold({_itemcost}, {_player}):
                    execute console command "/lp user %{_player}% parent add customrank"
                    rankPage({_player})
            else:
                send "{@servername} &cYou already own this rank!"
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}


        set {_itemcost} to 400
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 28 with glowing map named "<##008080>&lAstro Rank -> <##87CEEB>&lL<##9DDAF0>&lu<##B4E7F5>&ln<##CAF3FA>&la<##E0FFFF>&lr Rank Upgrade" with lore "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} has permission "group.astro":
                if {_player} doesn't have permission "group.lunar":
                    if buyitemGold({_itemcost}, {_player}):
                        execute console command "/lp user %{_player}% parent add lunar"
                        rankPage({_player})
                else:
                    play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                    send "{@servername} &cYou already own this rank!"
                             
            else:
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                send "{@servername} &cPrevious rank not owned!"


        make gui slot 29 with glowing map named "<##87CEEB>&lL<##9DDAF0>&lu<##B4E7F5>&ln<##CAF3FA>&la<##E0FFFF>&lr Rank -> <##FFD700>&lS<##FFDC23>&lo<##FFE246>&ll<##FFE768>&la<##FFEC8B>&lr Rank Upgrade" with lore "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} has permission "group.lunar":
                if {_player} doesn't have permission "group.solar":
                    if buyitemGold({_itemcost}, {_player}):
                        execute console command "/lp user %{_player}% parent add solar"
                        rankPage({_player})
                else:
                    play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                    send "{@servername} &cYou already own this rank!"
                            
            else:
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                send "{@servername} &cPrevious rank not owned!"


        make gui slot 30 with glowing map named "<##FFD700>&lS<##FFDC23>&lo<##FFE246>&ll<##FFE768>&la<##FFEC8B>&lr Rank -> <##D8BFD8>&lC<##DAC4DC>&le<##DCC9E1>&ll<##DDCEE5>&le<##DFD3E9>&ls<##E1D7ED>&lt<##E3DCF2>&li<##E4E1F6>&la<##E6E6FA>&ll Rank Upgrade" with lore "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} has permission "group.solar":
                if {_player} doesn't have permission "group.celestial":
                    if buyitemGold({_itemcost}, {_player}):
                        execute console command "/lp user %{_player}% parent add celestial"
                        rankPage({_player})
                else:
                    play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                    send "{@servername} &cYou already own this rank!"
                            
            else:
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                send "{@servername} &cPrevious rank not owned!"

        set {_itemcost} to 500
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 31 with glowing map named "<##D8BFD8>&lC<##DAC4DC>&le<##DCC9E1>&ll<##DDCEE5>&le<##DFD3E9>&ls<##E1D7ED>&lt<##E3DCF2>&li<##E4E1F6>&la<##E6E6FA>&ll Rank -> <##5907E0>&lG<##630EE0>&la<##6E16E0>&ll<##781DE0>&la<##8224E1>&lc<##8C2BE1>&lt<##9733E1>&li<##A13AE1>&lc<##AB41E1>&la Rank Upgrade" with lore "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} has permission "group.celestial":
                if {_player} doesn't have permission "group.galactica":
                    if buyitemGold({_itemcost}, {_player}):
                        execute console command "/lp user %{_player}% parent add galactica"
                        rankPage({_player})
                else:
                    play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                    send "{@servername} &cYou already own this rank!"
                         
            else:
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                send "{@servername} &cPrevious rank not owned!"

        set {_itemcost} to 1700
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 32 with glowing map named "<##5907E0>&lG<##630EE0>&la<##6E16E0>&ll<##781DE0>&la<##8224E1>&lc<##8C2BE1>&lt<##9733E1>&li<##A13AE1>&lc<##AB41E1>&la Rank -> <##FFD700>&lQ<##D8DB28>&lu<##B1DF50>&la<##8AE378>&ln<##63E79F>&lt<##3CEBC7>&lu<##15EFEF>&lm Rank Upgrade" with lore "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} has permission "group.galactica":
                if {_player} doesn't have permission "group.quantum":
                    if buyitemGold({_itemcost}, {_player}):
                        execute console command "/lp user %{_player}% parent add quantum"
                        rankPage({_player})
                else:
                    play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                    send "{@servername} &cYou already own this rank!"
                            
            else:
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                send "{@servername} &cPrevious rank not owned!"
        set {_itemcost} to 6000
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 33 with glowing map named "<##FFD700>&lQ<##D8DB28>&lu<##B1DF50>&la<##8AE378>&ln<##63E79F>&lt<##3CEBC7>&lu<##15EFEF>&lm Rank -> %rainbow("&lCustom Rank Upgrade")%" with lore "&7" and "&7[&fCost&7] %{_cost}%":
            if {_player} has permission "group.quantum":
                if {_player} doesn't have permission "group.customrank":
                    if buyitemGold({_itemcost}, {_player}):
                        execute console command "/lp user %{_player}% parent add customrank"
                        rankPage({_player})
                else:
                    play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                    send "{@servername} &cYou already own this rank!"            
            else:
                play sound "entity_villager_no" with volume 10 and pitch 10 to {_player}
                send "{@servername} &cPrevious rank not owned!"
        make gui slot 40 with arrow named "&8&lBack":
            execute {_player} command "/buystore"
    open last gui to {_player}


function sellwandPage(player: player):
    create a gui with virtual chest with 5 rows named "&8&l&nSellwands&3&l 💎%{goldamount::%{_player}'s uuid%}% Gems":
        make gui slot (integers from 0 to 44) with gray stained glass pane named " "
        make gui slot (0, 1, 9, 8, 7, 17, 27, 35, 36, 37, 35, 43, 44) with black stained glass pane named " "
        set {_itemcost} to 200
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 10 with blaze rod named "&e&l1x Sellwand" with lore "&f" and "&8&l﹁ &fSeasonal item!" and "&F" and "&7[&fCost&7] %{_cost}%":
            if buyitemGold({_itemcost}, {_player}):
                sellwand((0), (1), (100), "true", {_player})
                sellwandPage({_player})
        set {_itemcost} to 400
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1
        make gui slot 11 with blaze rod named "&e&l2x Sellwand" with lore "&f" and "&8&l﹁ &fSeasonal item!" and "&F" and "&7[&fCost&7] %{_cost}%":
            if buyitemGold({_itemcost}, {_player}):
                sellwand((0), (2), (100), "true", {_player})
                sellwandPage({_player})
        set {_itemcost} to 600
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1    
        make gui slot 12 with blaze rod named "&e&l3x Sellwand" with lore "&f" and "&8&l﹁ &fSeasonal item!" and "&F" and "&7[&fCost&7] %{_cost}%":
            if buyitemGold({_itemcost}, {_player}):
                sellwand((0), (3), (100), "true", {_player})
                sellwandPage({_player})
        set {_itemcost} to 800
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1   
        make gui slot 13 with blaze rod named "&e&l4x Sellwand" with lore "&f" and "&8&l﹁ &fSeasonal item!" and "&F" and "&7[&fCost&7] %{_cost}%":
            if buyitemGold({_itemcost}, {_player}):
                sellwand((0), (4), (100), "true", {_player})
                sellwandPage({_player})
        set {_itemcost} to 1000
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1   
        make gui slot 14 with blaze rod named "&e&l5x Sellwand" with lore "&f" and "&8&l﹁ &fSeasonal item!" and "&F" and "&7[&fCost&7] %{_cost}%":
            if buyitemGold({_itemcost}, {_player}):
                sellwand((0), (5), (100), "true", {_player})
                sellwandPage({_player})
        set {_itemcost} to 1200
        set {_cost} to "&b💎%{_itemcost}%"
        set {_cost} to "&4&m💎%{_itemcost}%&b 💎%({_itemcost}*{discount})%" if {discount} is less than 1   
        make gui slot 15 with blaze rod named "&e&l6x Sellwand" with lore "&f" and "&8&l﹁ &fSeasonal item!" and "&F" and "&7[&fCost&7] %{_cost}%":
            if buyitemGold({_itemcost}, {_player}):
                sellwand((0), (6), (100), "true", {_player})
                sellwandPage({_player})

        make gui slot 40 with arrow named "&8&lBack":
            execute {_player} command "/buystore"



    open last gui to {_player}